image:
- Visual Studio 2015
environment:
  matrix:
    # node.js
    - nodejs_version: "6.11.5"
    - nodejs_version: "7.10.1"
    - nodejs_version: "8.9.0"
    - nodejs_version: "9.0.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
  - node tools/coverage.js

after_test:
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $file = '.\test-results.xml'
      (New-Object 'System.Net.WebClient').UploadFile($url, (Resolve-Path $file))

build: off